-- ==============================================
-- SEED DATA — Portfolio Database
-- Generated by Claude (GenAI) for development
-- ==============================================

-- Projects
INSERT INTO projects (title, description, github_link, image_url, is_public, date_created) VALUES
('Weather Dashboard', 'A real-time weather dashboard that fetches data from OpenWeatherMap API and displays forecasts, temperature trends, and alerts.', 'https://github.com/devuser/weather-dashboard', 'https://storage.example.com/images/weather-dashboard.png', 'Yes', '2024-01-15 10:00:00'),
('Task Manager API', 'A RESTful API built in Go for managing tasks and projects with JWT authentication and role-based access control.', 'https://github.com/devuser/task-manager-api', 'https://storage.example.com/images/task-manager.png', 'Yes', '2024-03-10 09:00:00'),
('E-Commerce Storefront', 'A full-stack e-commerce application with product listings, cart management, and Stripe payment integration.', 'https://github.com/devuser/ecommerce-storefront', 'https://storage.example.com/images/ecommerce.png', 'Yes', '2024-06-20 14:00:00'),
('Portfolio CMS', 'A headless CMS for managing portfolio content with a Go backend, MySQL database, and REST API.', 'https://github.com/devuser/portfolio-cms', 'https://storage.example.com/images/portfolio-cms.png', 'Yes', '2024-09-05 11:00:00'),
('ML Price Predictor', 'A machine learning model that predicts housing prices using linear regression, trained on public datasets.', 'https://github.com/devuser/ml-price-predictor', 'https://storage.example.com/images/ml-predictor.png', 'No', '2024-11-01 16:00:00');

-- Work Experience
INSERT INTO work_experience (job_title, company_name, description, role_type, is_public, date_started, date_ended) VALUES
('Junior Software Engineer', 'TechNova Solutions', 'Developed and maintained internal tooling using Go and PostgreSQL. Collaborated with senior engineers on microservices architecture.', 'full-time', 'Yes', '2022-06-01 00:00:00', '2023-08-31 00:00:00'),
('Software Engineering Intern', 'CloudBridge Inc.', 'Built REST APIs in Python and assisted in migrating legacy services to AWS Lambda. Wrote unit tests and documentation.', 'internship', 'Yes', '2022-01-10 00:00:00', '2022-05-20 00:00:00'),
('Backend Engineer', 'DataStream Labs', 'Led backend development for a real-time analytics platform. Designed database schemas, optimized SQL queries, and integrated third-party APIs.', 'full-time', 'Yes', '2023-09-15 00:00:00', NULL),
('Freelance Developer', 'Self-Employed', 'Delivered custom web applications and APIs for small business clients. Managed projects end-to-end from requirements to deployment.', 'contract', 'Yes', '2021-03-01 00:00:00', '2022-05-31 00:00:00');

-- Skills
INSERT INTO skills (name, thumbnail, category, position) VALUES
('Go', 'https://storage.example.com/skills/go.png', 'Programming Languages', 1),
('Python', 'https://storage.example.com/skills/python.png', 'Programming Languages', 2),
('JavaScript', 'https://storage.example.com/skills/javascript.png', 'Programming Languages', 3),
('MySQL', 'https://storage.example.com/skills/mysql.png', 'Databases', 1),
('PostgreSQL', 'https://storage.example.com/skills/postgresql.png', 'Databases', 2),
('Docker', 'https://storage.example.com/skills/docker.png', 'DevOps', 1),
('AWS', 'https://storage.example.com/skills/aws.png', 'Cloud Tools', 1),
('React', 'https://storage.example.com/skills/react.png', 'Frameworks', 1),
('TensorFlow', 'https://storage.example.com/skills/tensorflow.png', 'AI/ML', 1);

-- Certifications
INSERT INTO certifications (name, company, verification_url, date_issued, date_expiration, is_public) VALUES
('AWS Certified Developer – Associate', 'Amazon Web Services', 'https://aws.amazon.com/verification/ABC123', '2023-04-15 00:00:00', '2026-04-15 00:00:00', 'Yes'),
('Google Associate Cloud Engineer', 'Google', 'https://google.com/verification/XYZ789', '2023-09-01 00:00:00', '2026-09-01 00:00:00', 'Yes'),
('Docker Certified Associate', 'Docker Inc.', 'https://docker.com/verification/DEF456', '2024-01-20 00:00:00', NULL, 'Yes');

-- Blog Posts
INSERT INTO blog_posts (title, description, content_url, thumbnail, slug, is_public, date_created) VALUES
('Getting Started with Go Modules', 'A beginner-friendly guide to understanding Go modules, dependency management, and how go.mod works.', 'https://storage.example.com/blog/getting-started-go-modules.md', 'https://storage.example.com/blog/thumbnails/go-modules.png', 'getting-started-with-go-modules', 'Yes', '2024-02-10 08:00:00'),
('Designing a RESTful API in Go', 'Best practices for structuring a Go REST API with clean architecture, middleware, and error handling.', 'https://storage.example.com/blog/designing-restful-api-go.md', 'https://storage.example.com/blog/thumbnails/rest-api-go.png', 'designing-a-restful-api-in-go', 'Yes', '2024-04-22 09:30:00'),
('MySQL vs PostgreSQL: Which Should You Choose?', 'A practical comparison of MySQL and PostgreSQL covering performance, features, and use cases.', 'https://storage.example.com/blog/mysql-vs-postgresql.md', 'https://storage.example.com/blog/thumbnails/mysql-vs-postgres.png', 'mysql-vs-postgresql-which-should-you-choose', 'Yes', '2024-07-15 10:00:00'),
('Docker Compose for Local Development', 'How to use Docker Compose to spin up multi-container development environments quickly and reliably.', 'https://storage.example.com/blog/docker-compose-local-dev.md', 'https://storage.example.com/blog/thumbnails/docker-compose.png', 'docker-compose-for-local-development', 'No', '2024-10-03 14:00:00');

-- ==============================================
-- JUNCTION TABLES
-- Note: IDs reference the AUTO_INCREMENT values
-- above, assuming clean insert order from 1
-- ==============================================

-- skill_project (Skills linked to Projects)
INSERT INTO skill_project (skill_id, project_id) VALUES
(1, 1), -- Go -> Weather Dashboard
(3, 1), -- JavaScript -> Weather Dashboard
(1, 2), -- Go -> Task Manager API
(4, 2), -- MySQL -> Task Manager API
(3, 3), -- JavaScript -> E-Commerce Storefront
(8, 3), -- React -> E-Commerce Storefront
(1, 4), -- Go -> Portfolio CMS
(4, 4), -- MySQL -> Portfolio CMS
(2, 5), -- Python -> ML Price Predictor
(9, 5); -- TensorFlow -> ML Price Predictor

-- skill_experience (Skills linked to Work Experience)
INSERT INTO skill_experience (skill_id, experience_id) VALUES
(1, 1), -- Go -> Junior Software Engineer @ TechNova
(5, 1), -- PostgreSQL -> Junior Software Engineer @ TechNova
(2, 2), -- Python -> Intern @ CloudBridge
(7, 2), -- AWS -> Intern @ CloudBridge
(1, 3), -- Go -> Backend Engineer @ DataStream Labs
(4, 3), -- MySQL -> Backend Engineer @ DataStream Labs
(6, 3), -- Docker -> Backend Engineer @ DataStream Labs
(2, 4), -- Python -> Freelance Developer
(3, 4); -- JavaScript -> Freelance Developer

-- skill_blog (Skills linked to Blog Posts)
INSERT INTO skill_blog (skill_id, post_id) VALUES
(1, 1), -- Go -> Getting Started with Go Modules
(1, 2), -- Go -> Designing a RESTful API in Go
(4, 3), -- MySQL -> MySQL vs PostgreSQL
(5, 3), -- PostgreSQL -> MySQL vs PostgreSQL
(6, 4); -- Docker -> Docker Compose for Local Development

-- project_blog (Projects linked to Blog Posts)
INSERT INTO project_blog (project_id, post_id) VALUES
(2, 2), -- Task Manager API -> Designing a RESTful API in Go
(4, 2), -- Portfolio CMS -> Designing a RESTful API in Go
(4, 3); -- Portfolio CMS -> MySQL vs PostgreSQL